spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: embedded
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
      schema-locations: classpath:/org/springframework/batch/core/schema-mysql.sql
batch:
  job:
    enabled: false